### ISSUE TITLE
Statistical data page - categorical mutually exclusive variables

### ISSUE THREAD

**Issue by Lizzy618** [legalscienceio/monqcle#6]
Categorical mutually exclusive questions are not rendering properly (i.e. should be numbered within one column, representing one variable) and do not match the Codebook. Only Categorical Check All That Apply questions should be separated out by individual answer choice/variable.

**Comment by seekayel** [comment]
Is the issue that the export doesn't match the code book or that the column format changed?

**Comment by Lizzy618** [comment]
Both - a categorical mutually exclusive question should be 1 variable (so 1 column in the export) and the answer choices should be represented by the numbers defined in the Codebook. 

Instead, the export is depicting categorical mutually exclusive questions like categorical check all that apply questions, in which each individual answer choice is a different variable/column in the export

**Comment by Lizzy618** [comment]
Attempting to attach an example of the incorrect vs. correct stat page

Stat Data Bug1 - shows how the **categorical mutually exclusive** question is currently appearing in the stat data export (incorrect).
Stat Data Bug2 - shows the codebook for that **categorical mutually exclusive** question, representing a numerical value for each answer choice
Stat Data Bug 2- Correct - shows how the categorical mutually exclusive question should appear in the stat data export, as one variable with numbers representing the answer choice that correspond to the codebook

[Stat Data Bug1.xlsx](https://github.com/legalscienceio/monqcle/files/1038724/Stat.Data.Bug1.xlsx)
[Stat Data Bug2.docx](https://github.com/legalscienceio/monqcle/files/1038725/Stat.Data.Bug2.docx)
[Stat Data Bug3 - Correct.xlsx](https://github.com/legalscienceio/monqcle/files/1038726/Stat.Data.Bug3.-.Correct.xlsx)

**Comment by Lizzy618** [comment]
Update: spoke with PSP & Mark - need to the Stat page to match the Codebook, so it is easiest to have the Stat page display categorical mutually exclusive questions in one column. This is the immediate resolution

Mark & I discussed future edits where both options are available and/or we look more into what our users want. Also discussed moving the Codebook download to the export tab so that it makes sense to users that it should be used in conjunction with the Stat page.
