### ISSUE TITLE
Question options (expand/collapse, edit, add sub question) etc not appearing

### ISSUE THREAD

**Issue by CateDavie** [legalscienceio/monqcle#69]
I am adding questions to the Direct Dispensing dataset right now and I noticed that whenever I add a question the options to the side of the questions disappear and only expand/collapse appear. They show up if I refresh the page though. 

https://monqcle.com/dataset/59afef96f5f53c1c308b4567/show

Thanks!!!!

**Comment by blackcorvidae** [comment]
we will use #741 to clean this up, thanks.  Closing for now, I'll include you in the other ticket, Cate.
