### ISSUE TITLE
Adding viewer to dataset created by a group

### ISSUE THREAD

**Issue by Lizzy618** [legalscienceio/monqcle#7]
I had added a person as a "viewer" to one of the 40 cities datasets created by the LS group. I want them to only have viewer access to that one dataset. Instead, it automatically adds her to the entire group so she has viewer access to all the datasets for that group.

This is something we need to fix so that we can let clients have viewer access to their one dataset but nothing else.

**Comment by blackcorvidae** [comment]
I can confirm this, happened in my test too.

**Comment by korostelevm** [comment]
The person does get added to the group but none of the group's other assets. Cant seem to reproduce the case where adding someone to a dataset directly adds to all group's datasets
