### ISSUE TITLE
Law Library Not Working

### ISSUE THREAD

**Issue by CateDavie** [legalscienceio/monqcle#74]
The law library isn't working for me. I am in the Direct Dispensing dataset (https://monqcle.com/dataset/direct-dispensing-laws-for-physician-assistants/code/59ee1532f5f53c6f4f8b4568). When I click on browse nothing shows up and if I search a law and click on a result nothing happens. 

Thanks!!!

**Comment by CateDavie** [comment]
![Screen Shot 2017-10-23 at 12.17.08 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5924986c8110270020a3f879/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236456f06b7191a379ed0c2a56415f46bc21254d58eeb9cb74fce36f34985619e8d86c5e27933b16fdbfd319b702ba208c1ad7b6bd8c49c0fa2137a5dad11b61435c52dcbd4f3fb29842c259f34be94a52a116316be277376e0a.png)

**Comment by gong4494** [comment]
This is fixed in legalscienceio/state_scrapers/issues/192.
