### ISSUE TITLE
Map view isn't working in Monqcle

### ISSUE THREAD

**Issue by CateDavie** [legalscienceio/monqcle#83]
Map view isn't working in Monqcle- may be time zone issue.

**Comment by CateDavie** [comment]
![Screen Shot 2017-12-06 at 2.08.17 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5924986c8110270020a3f879/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216454f56b7191a37af112234f5e585ecc3c4a4356bcbbd671f3e57862804e0ee4d06c0c21c03a40abe98417bc01ba27de1d85b7ba8f4cd2f42f67b6d5db1063474f4dcbed5727a19141c95df749e44552a7153363e0712431.png)

**Comment by CateDavie** [comment]
![Screen Shot 2017-12-06 at 2.07.57 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5924986c8110270020a3f879/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216454f56b7191a37af1122c4f5a585ecc3c4a4356bcbbd671f3e57862804e0ee4d06c0c21c03a40abe98417bc01ba27de1d85b7ba8f4cd2f42f67b6d5db1063474f4dcbed5727a19e41c95df749e44552a7143061ef7f2431.png)

**Comment by korostelevm** [comment]
Need to update the timeslider to use moment.js with timezones. Should really update this map to use the plugin version, but this is a simple fix for now
