### ISSUE TITLE
Monqcle Not Saving

### ISSUE THREAD

**Issue by CateDavie** [legalscienceio/monqcle#87]
I am working on Cityhealth: Nutrition Standards for City Procurement v. 2.0 (https://monqcle.com/dataset/40-cities-nutritional-standards-for-city-procurement-1475439271/code/591b55f5f7d1b6e748334873)

Monqcle won't let me save changes to the legal text. Thanks!

**Comment by blackcorvidae** [comment]
@korostelevm @gong4494 any ideas on this one?

Thanks.

**Comment by gong4494** [comment]
I'm on it. It was due to the Jurisdiction fix we did last time. I can do a fix on the controller first then check if the data need to be fixed later
