### ISSUE TITLE
Coding review tool not showing all questions or showing the ranking as a question

### ISSUE THREAD

**Issue by CateDavie** [legalscienceio/monqcle#92]
I am working in CityHealth Complete Streets https://monqcle.com/dataset/5735b36cf7d1b641210a6232/show

When I am using the coding review tool I noticed two issues 
(1) Not all of the questions are showing (see https://monqcle.com/coding_review/run/5735b36cf7d1b641210a6232). Seven questions should be showing but only 6 questions show. 

(2) This only appears to be happening in Fresno so I don't know if it's a big deal but the ranking is showing up in the coding review as two extra questions (see https://monqcle.com/coding_review/run/5735b36cf7d1b641210a6232)

**Comment by CateDavie** [comment]
Oops!! Sorry that first issue is not an issue at all! Thanks!!!

**Comment by gong4494** [comment]
The second issue was because the ranking answer was changed so it was showing.
